### ISSUE TITLE
Patient wants to view sources for information provided in the application (User Story)

### ISSUE THREAD

**Issue by austinduncan1** [awasserman14/OsteoApp#6]
Patient wants to see the sources for information contained in the app in order to verify their reputability

- [ ] Create View to display this information
- [ ] Display references for all information used in the application

![Screen Shot 2018-01-10 at 2.20.39 PM.png](https://images.zenhubusercontent.com/587e927851aa2c30577247d1/03b12e33-99f6-4cb0-9ffb-6b8dfb9afd5e)

[https://app.zenhub.com/files/112115242/1ca8ffa1-a3c3-44ec-a762-971aaf3dee06/download](https://app.zenhub.com/files/112115242/1ca8ffa1-a3c3-44ec-a762-971aaf3dee06/download)

**Comment by ghost** [comment]
Done
