### ISSUE TITLE
Patient wants to see how treatment options are calculated (User Story)

### ISSUE THREAD

**Issue by austinduncan1** [awasserman14/OsteoApp#7]
A patient wants to find out how the treatment options they have been presented with are determined

- [ ] Create view to display the information
- [ ] Create documentation for algorithm used to compute this

![Screen Shot 2018-01-10 at 2.23.09 PM.png](https://images.zenhubusercontent.com/587e927851aa2c30577247d1/f99e41c2-72b4-44f3-992a-03e6ee45a2e8)

[https://app.zenhub.com/files/112115242/a56e5273-5731-4966-baa1-b651f4cbadea/download](https://app.zenhub.com/files/112115242/a56e5273-5731-4966-baa1-b651f4cbadea/download)

**Comment by ghost** [comment]
Algorithm is limited at this stage of development due to professional contraints
