### ISSUE TITLE
Patient wants to view past survey results (User Story)

### ISSUE THREAD

**Issue by austinduncan1** [awasserman14/OsteoApp#9]
A patient wants to view their previous survey results in order to compare the effects of different values

- [ ] Create a View for displaying historical results
- [ ] Historical results are to be stored on the device to avoid conflicts with HIPPA

![Screen Shot 2018-01-10 at 2.27.37 PM.png](https://images.zenhubusercontent.com/587e927851aa2c30577247d1/ad62e0ee-ccff-44ba-8e78-9834244b37e2)

[https://app.zenhub.com/files/112115242/d7252c40-96e7-47fa-b9ed-361baf91b645/download](https://app.zenhub.com/files/112115242/d7252c40-96e7-47fa-b9ed-361baf91b645/download)

**Comment by ghost** [comment]
Accomplished
